const actionTypes = {
  NAME_FALSE: "NAME_FALSE",
  NAME_TRUE: "NAME_TRUE",

  SURNAME_FALSE: "SURNAME_FALSE",
  SURNAME_TRUE: "SURNAME_TRUE",

  PHONE_FALSE: "PHONE_FALSE",
  PHONE_TRUE: "PHONE_TRUE",

  SITE_FALSE: "SITE_FALSE",
  SITE_TRUE: "SITE_TRUE",

  DESCRIPTION_FALSE: "DESCRIPTION_FALSE",
  DESCRIPTION_TRUE: "DESCRIPTION_TRUE",

  STACK_FALSE: "STACK_FALSE",
  STACK_TRUE: "STACK_TRUE",

  PROJECT_FALSE: "PROJECT_FALSE",
  PROJECT_TRUE: "PROJECT_TRUE",
};

export default actionTypes;

/* name, surname, phone, site, description, stack, project */
